# Railway configuration for Chinese Learning App
# This deploys the frontend - server will be deployed separately

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm run preview"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables
[environment]
VITE_API_URL = "${{API_URL}}"