# Railway configuration for API Server

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables will be set through Railway dashboard
[environment]
NODE_ENV = "production"